const { createClient } = require('@supabase/supabase-js');

const supabaseUrl = 'https://idpmrjjalhnpsxpfugph.supabase.co';
const supabaseServiceKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcG1yamphbGhucHN4cGZ1Z3BoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NzY2NTY2NywiZXhwIjoyMDkzMjQxNjY3fQ.YR1d6swxo1BbQ3ixTYB43KtZL5ure__R4wuqAkd7by4';
const supabase = createClient(supabaseUrl, supabaseServiceKey);

async function setup() {
    const sql = `
        CREATE TABLE IF NOT EXISTS revisados (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            selb TEXT NOT NULL,
            ts TIMESTAMPTZ DEFAULT now(),
            user_email TEXT
        );
        ALTER TABLE revisados ENABLE ROW LEVEL SECURITY;
        DROP POLICY IF EXISTS "Permitir tudo para autenticados" ON revisados;
        CREATE POLICY "Permitir tudo para autenticados" ON revisados FOR ALL TO authenticated USING (true);
    `;
    const { error } = await supabase.rpc('exec_sql', { sql_query: sql });
    if (error) {
        console.log("⚠️ SQL Manual Necessário no Dashboard:");
        console.log(sql);
    } else {
        console.log("✅ Tabela 'revisados' pronta!");
    }
}
setup();
